image: shippedrepos-docker-base-images.bintray.io/spark-node-base:4.0.0
git:
  path: github.com/sn-codes/python-spark
script:
  - echo "build commands"
  - .shipped/build
  - .shipped/test
clone:
  path: github.com/sn-codes/python-spark
build:
  image: shippedrepos-docker-base-images.bintray.io/spark-node-base:4.0.0
  commands:
    - echo "build commands"
    - .shipped/build
    - .shipped/test
publish:
  docker:
    file: ./Dockerfile
    username: $$docker_user
    password: $$docker_key
    registry: $$docker_registry
    repo: $$docker_repo
    email: $$docker_user_email
    tag: $$COMMIT
    


notify:
  webhook:
    image: shippedrepos-docker-drone.bintray.io/drone-webhook
    urls:
      - "https://api.ciscoshipped.io/webhooks/drone"
    on_success: true
    on_failure: true
